use_frameworks!

platform :ios, '12.0'

target 'SFNetworkManager_Example' do
  pod 'SFNetworkManager', :path => '../'
  
  target 'SFNetworkManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
